Fix 4.2 upgrade
wazuh/wazuh-docker pull request #509
Opened 2021-09-02 15:41 UTC by DFolchA

Closes #505 

This PR fixes a problem when upgrading wazuh-docker to 4.2.0 where the persistent volume in `/var/ossec/queue` caused  the manager to be unable to start.

2021-09-02 15:53 UTC, okynos requested changes
Minor change, GJ.

2021-09-02 15:53 UTC, okynos commented on wazuh-odfe/config/etc/cont-init.d/0-wazuh-init
> +      exec_cmd "rm -rf ${del_file}"
Remove `-r` for file removal.

2021-09-03 07:43 UTC, DFolchA commented on wazuh-odfe/config/etc/cont-init.d/0-wazuh-init
> +      exec_cmd "rm -rf ${del_file}"
Done in 413dd71

2021-09-03 09:26 UTC, okynos approved these changes
LGTM.

2021-09-03 09:37 UTC, merged