Change directories structure
wazuh/wazuh-docker pull request #603
Opened 2022-03-30 17:11 UTC by vcerenu

This PR modifies the directory structure of the repository, to order the deployment of multi-node and single-node stacks, in addition to organizing the build of Wazuh Docker images.

2022-03-30 17:23 UTC, teddytpc1 requested changes

2022-03-30 17:23 UTC, teddytpc1 commented on multi-node/volume-migrator.sh
> +           -v $2_worker-filebeat-var:/to \
Nice!

2022-03-30 17:23 UTC, teddytpc1 commented on README.md
> +│   │   └── wazuh_indexer_ssl_certs
Update tree (without cert files)

2022-03-30 17:40 UTC, teddytpc1 approved these changes
LGTM

2022-03-31 09:16 UTC, alberpilot requested changes
- The folder `indexer_certs_creator` doesn't match the other folder format name. `indexer-certs-creator`.
- Remove empty lines from the main README variables sections. 
- The directory structure is broken
- Add README under `multi-node`, `single-node`, `build-docker-images`. The new `indexer-certs-creator` should have a README too. 
- Additionally `generate-indexer-certs.yml` doesn't work:
```
~/repositories/wazuh-docker/multi-node   change-directories ●  docker-compose -f generate-indexer-certs.yml up                
Creating network "multi-node_default" with the default driver
Pulling generator (wazuh/wazuh-certs-generator:0.0.1)...
0.0.1: Pulling from wazuh/wazuh-certs-generator
08c01a0ec47e: Pull complete
6d34cc3bb0a2: Pull complete
bcad6faac775: Pull complete
c7fbc190910a: Pull complete
b747db0e8163: Pull complete
37cacab0e3bb: Pull complete
Creating multi-node_generator_1_a2e47470a1d4 ... done
Attaching to multi-node_generator_1_c9056ee06162
generator_1_c9056ee06162 | 31/03/2022 09:15:19 ERROR: No configuration file found. /unattended_installer/install_functions/config.yml.
generator_1_c9056ee06162 | Moving created certificates to destination directory
generator_1_c9056ee06162 | cp: cannot stat '/unattended_installer/install_functions/certs/*': No such file or directory
generator_1_c9056ee06162 | changing certificate permissions
```

2022-03-31 18:00 UTC, teddytpc1 approved these changes
LGTM

2022-04-01 09:10 UTC, alberpilot approved these changes

2022-04-01 09:10 UTC, merged