Test PR
wazuh/wazuh-docker pull request #669
Opened 2022-06-03 18:52 UTC by vcerenu

Test PR

2022-06-13 19:11 UTC, teddytpc1 submitted a review, later dismissed
LGTM

2022-06-14 16:01 UTC, teddytpc1 submitted a review, later dismissed
LGTM

2022-06-15 12:05 UTC, teddytpc1 approved these changes
LGTM

2022-06-17 08:24 UTC, okynos requested changes

2022-06-17 08:24 UTC, okynos commented on .github/.goss.yaml
> +    - 4.3.4-1
It is 4.3.3 or 4.3.4?

2022-06-17 08:24 UTC, okynos commented on .env
> +WAZUH_VERSION=4.3.3
Same

2022-06-20 13:42 UTC, alberpilot approved these changes

2022-06-20 13:42 UTC, merged