Bump 4.3 to 4.3.7
wazuh/wazuh-docker pull request #708
Opened 2022-08-12 15:33 UTC by vcerenu

This PR bumps 4.3 to 4.3.7.

2022-08-12 15:40 UTC, teddytpc1 approved these changes
LGTM.
We'll have to wait for the packages to re-run the tests.

2022-08-12 15:42 UTC, teddytpc1 requested changes

2022-08-12 15:42 UTC, teddytpc1 commented on .github/.goss.yaml
> +    - 7-1
@vcerenu please fix this.

2022-08-12 15:44 UTC, vcerenu commented on .github/.goss.yaml
> +    - 7-1
fixed

2022-08-16 06:41 UTC, alberpilot approved these changes

2022-08-16 10:37 UTC, okynos approved these changes

2022-08-17 06:23 UTC, merged