Merge 4.3 in 4.4 branch
wazuh/wazuh-docker pull request #758
Opened 2022-11-30 18:30 UTC by vcerenu

This PR merges all changes made to the 4.3 branch into the 4.4 branch

2022-11-30 18:34 UTC, teddytpc1 requested changes

2022-11-30 18:34 UTC, teddytpc1 commented on build-docker-images/build-images.sh
> +WAZUH_IMAGE_VERSION=4.3.10
This version should be 4.4.0.

2022-11-30 18:35 UTC, vcerenu commented on .env
> +WAZUH_IMAGE_VERSION=4.3.10
fixed

2022-11-30 18:35 UTC, vcerenu commented on build-docker-images/build-images.sh
> +WAZUH_IMAGE_VERSION=4.3.10
fixed

2022-12-01 15:22 UTC, alberpilot approved these changes

2022-12-01 15:23 UTC, merged